### ISSUE TITLE
As a user, I would like to login so that I can see my dashboard

### ISSUE THREAD

**Issue by waiyan13** [techyangon/may-jls-api#3]
## Acceptance Criteria

Feature: Authentication

    Scenario: the user goes to app URL
        Given the user has no credentials
        When the user visits the URL
        Then the user should be redirected to login

    Scenario: the user goes to app URL
        Given the user has correct credentials
        When the user logs in
        Then the user should be redirected to dashboard

    Scenario: the user goes to app URL
        Given the user has incorrect credentials
        When the user logs in
        Then the user should be prompted with information to correct.

## Tasks List

- [ ] Create route for authentication
- [ ] Setup `users` table
- [ ] Setup seeding dataa
- [ ] Migrate database tables
- [ ] Process login credentials
- [ ] Setup access token/ refresh token generation
